### PR TITLE
Add function cat_anon()

### PR DESCRIPTION
**Pull request by Avatoo**
Anonymise category levels e.g convert `James, Bob, Clair, Clair` to `x_1, x_2, x_3, x_3`

### CODE REVIEW

**Comment by dougmet** [comment]
Thanks Ava!

**Comment by dougmet** [comment]
Need to get to a laptop to test. Does this return a categorical series or strings? I think I would expect cats.

**Comment by Avatoo** [comment]
It returns object dtype, which means strings? In this regard, `cat_anon()` is exactly in line with `cat_lump()`. Should it not?

**Comment by dougmet** [comment]
ah OK, if that's what the others do then great!

**Review by dougmet — APPROVED** [review]

**Comment by Avatoo** [comment]
Thanks Doug :) I don't have strong opinions on types. It feels pandas itself can cover a fair amount of job and this package sits on top. Once the functionality is intact, maybe we can reflect on context and refactor things a bit?

**Comment by wkostelecki** [comment]
I think the goal should be to eventually always return categorical series. Best not to use cat_lump as a reference for this!

**Pull request merged**
